services:
#    task.example:
#        class: Multiservices\TaskBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   
    taskbundle_datatable.tareas:
        class: Multiservices\TaskBundle\Datatables\TareaDatatable
        parent: sg_datatables.datatable.abstract 
    taskbundle.form.handler.tarea:
        class: AppBundle\Form\Handler\FormHandler
        arguments: ["@doctrine.orm.entity_manager","@form.factory","@taskbundle.form.tareatype"]
    taskbundle.form.tareatype:
        class: Multiservices\TaskBundle\Form\TareaType
