services:
#    task.example:
#        class: Multiservices\TaskBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   
    lex_datatables.tarea:
        class: Multiservices\TaskBundle\Datatables\TareaDatatable
        tags:
            - { name: sg.datatable.view }        
    taskbundle.form.handler.tarea:
        class: AppBundle\Form\Handler\FormHandler
        arguments: ["@doctrine.orm.entity_manager","@form.factory","@taskbundle.form.tareatype"]
    taskbundle.form.tareatype:
        class: Multiservices\TaskBundle\Form\TareaType
