#para rutas front
clientes:
    path:      /clientes/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
clientes_api:
    type: rest
    resource: "@ArxisContableBundle/Controller/ClienteController.php"
    options:
        expose: true
    prefix: api 
clientes_results:
    path:     /clientes/results
    defaults: { _controller: "ArxisContableBundle:Cliente:results" }
    methods:  [GET, POST]
clientes_edit:
    path:     /clientes/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
