#para rutas front
contactos:
    path:      /contactos/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
contactos_api:
    type: rest
    resource: "@ArxisContableBundle/Controller/ContactoController.php"
    options:
        expose: true
    prefix: api 
contactos_results:
    path:     /contactos/results
    defaults: { _controller: "ArxisContableBundle:Contacto:results" }
    methods:  [GET, POST]
contactos_edit:
    path:     /contactos/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
