# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.readable_html_enum_value:
      class: AppBundle\Twig\Extension\ReadableHtmlEnumValueExtension
      arguments: [%doctrine.dbal.connection_factory.types%]
      tags:
          - { name: twig.extension }
    twig.extension.url64:
      class: AppBundle\Twig\Extension\Base64Extension
      tags:
          - { name: twig.extension }
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    my.fos.user_provider:
        class:     AppBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebookId }]
    #app_oauth_server.storage:
    #    class: AppBundle\Storage\AppOAuthStorage
    #    arguments: ["@fos_oauth_server.client_manager", "@fos_oauth_server.access_token_manager", "@fos_oauth_server.refresh_token_manager", "@fos_oauth_server.auth_code_manager", "@?fos_oauth_server.user_provider", "@security.encoder_factory", "@doctrine.orm.entity_manager","@service_container"]
    #app_oauth_server.server:
    #    class: AppBundle\Security\AppOAuth2
    #    arguments: ["@app_oauth_server.storage", "%fos_oauth_server.server.options%"]
    
    api.oauth.facebook_extension:
        class: AppBundle\OAuth\FacebookGrantExtension
        arguments:
            - '@my.fos.user_provider'
        tags:
            - { name: fos_oauth_server.grant_extension, uri: 'https://facebook.com/' }
    twig.extension.readable_html_enum_value:
      class: AppBundle\Twig\Extension\ReadableHtmlEnumValueExtension
      arguments: [%doctrine.dbal.connection_factory.types%]
      tags:
          - { name: twig.extension }
    twig.extension.url64:
      class: AppBundle\Twig\Extension\Base64Extension
      tags:
          - { name: twig.extension }      
    #HANDLERS
    #appbundle.form.handler.usuario:
    #   class: AppBundle\Form\Handler\FormHandler
    #   arguments: ["@doctrine.orm.entity_manager","@form.factory","@appbundle.form.usuariotype"]
    #appbundle.form.usuariotype:
    #    class: AppBundle\Form\UsuarioType        