#para rutas front
tarea:
    path:      /tarea/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
tarea_api:
    type: rest
    resource: "@TaskBundle/Controller/TareaController.php"
    options:
        expose: true
    prefix: api 
tarea_results:
    path:     /tarea/results
    defaults: { _controller: "TaskBundle:Tarea:results" }
    methods:  [GET, POST]
tarea_edit:
    path:     /tarea/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
