<?php

namespace Multiservices\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends EntityRepository
{
    public function inbox($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t'
                    . ' FROM TaskBundle:Tarea t '
                    . 'where t.assignedto=:user'
                    . ' ORDER BY t.created DESC')
            ->setParameter(":user", $user)
            ->getResult();
    }
}
