#para rutas front
restaurant:
    path:      /restaurant/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true

#rutas del back o api         
restaurant_api:
    type: rest
    resource: "@AComerBundle/Controller/RestaurantController.php"
    options:
        expose: true
    prefix: api
restaurant_results:
    path:     /restaurant/results
    defaults: { _controller: "AComerBundle:Restaurant:results" }
    methods:  [GET, POST]

