#para rutas front
formaspagos:
    path:      /formaspagos/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
formaspagos_api:
    type: rest
    resource: "@PayPayBundle/Controller/FormasPagosController.php"
    options:
        expose: true
    prefix: api 
formaspagos_results:
    path:     /formaspagos/results
    defaults: { _controller: "PayPayBundle:FormasPagos:results" }
    methods:  [GET, POST]
formaspagos_edit:
    path:     /formaspagos/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
