#para rutas front
productos:
    path:      /productos/{page}
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    requirements:
        page: \d+|new
    options:
        expose: true
#rutas del back o api         
productos_api:
    type: rest
    resource: "@PayPayBundle/Controller/ProductosController.php"
    options:
        expose: true
    prefix: api 
productos_results:
    path:     /productos/results
    defaults: { _controller: "PayPayBundle:Productos:results" }
    methods:  [GET, POST]
productos_edit:
    path:     /productos/{page}/edit
    defaults:  { _controller: AppBundle:Default:inicio, page: index }
    methods:  [GET, POST]
    options:
        expose: true
